notifications:
  email: false

# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: XjCS9qu3WTx0Yswp1aObQ6Acxln8pbVTzYBj+YComuav/DWUwQG2JWL/8mxzQzPzgEYZjQRhkwPxrKLJu79og5M957kT4xacFtM0TXiDSJR/84HzkTlal7NH5nTp7yccL0eanCyWp+PSt06nNRPokDy5FLhnyyTrSkodEAn3PdriH1hE2cfre2oqPN0Y6RHPax9jREGR9KH7rS3m4NCjXr7cF5fOgzbhDETGtzFRj7i4BVi8sQl5TOVQtsJMEVUsmZFZVCVTtXHkmTeUY1k0HxL7SvsrRurLn4plL5XO84tJ1c/VhnWtQ8A4EcNt1+uNR7rf33juVThjaJXiaSMAzi9e19PcrS0J7WQ5cRuZgcQYdqK5l7jFUCqgDnKspnBuWkAiPI39Iw2wijl28QwU2vBEA6vlsi4k3GBStQ4rs6AHm2p60djYU8d4RFDLiV5WpoccxEiQFSjpyOrE1T0xJuLWVIbouRCBscZJQwODaRHvm95jyDZe1Nx41IksB5pDABtypAOxvHhnR/bIfxnx4vTBTzyCv5S7x6QxF0Zg9KuhRO+Q3hvqKPHWe3OCV3bcCZCYdpRxp/jEzva4UA1gvNppDsIj3V5ScmjrjRw59L5qo2ac6q/hLGDkrF2Np1ZaPhvJc/9uTjunTGNUA2WXmABh7itdBNelw5MOOrDRZ+M=

# Language options
language: node_js
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
node_js:
  - 4
before_script:
  - npm prune
script:
  - npm run cover
  - npm run lint

# Npm publish options
before_deploy:
  - npm run build
deploy:
  skip_cleanup: true # keep the devDependencies
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: MFb7BLy7J6MeZyNfkvDjCLnri/0+aBlJCcrrBECPa0SKYJdgXAEy2ziLfvNFFshWlwDZyrxFv5lM3AOl62O22jWH2TwAjc9ur9PS0CArBUFRLqFIx7Yrtkg/fOUQP/O6V6oYCMBn1JrKoIcAJQftjPjHuzt2c4znicfcBJ4ZCP8X6Ji9u76gWpCzUPA/8M4BplSokPqE+SQPlSZXZrLFsZ3AyYMxRkT2QGjwrHAYg5MDnyyt2tZ4FzZQ09l/Fpxq/AvokzHeZT/pvEflmr3ytrJ55kuwofzHppR/rpXOQq7SI2xASG6StGPY6WQ0Beb0mm5iVALBcrB+iKH4u9trSi4FGr2xpTXfXEoHfVcrxYVO6UMbh5nN9eDP5aGnrj0Hk4NfX6+/4eG26Mxem7+Y6eLTA2Wxiv847DDSpMNUYO8ymQL6W7/V7PEt3vwN/0EKWlwWG/LujHQrrmhha7RHnBU39J4qVwuHj7kgcxwXFi7aF5qRZZByjYE56IYww2rt24V4xdE0O/hqc+51dV2vcBayFJecwN3V30Vk0UJ21x6zc8pv8mO2JCLyIzM5JJqA5AVZlyzGEO+7IO3SUauja4Cv0fH+W7GI3cjBPP3zGwvu4z4pXTNWy2bgfqEjLg6H3pJTgmq8kt7sKYfdq+ornbPwVxDatr6mt7xbxgywKHI=
  on:
    node: 4
